### ISSUE TITLE
[bug]: sign in with google flow not working

### ISSUE THREAD

**Issue by Ngoakor12** [Dev-CasperTheGhost/home-inventory#118]
**Describe the bug**
sign in with google flow not working

**To Reproduce**

1. Visit site
2. Press "sign in with google" and you'll see

**Expected behavior**
I should be sign in or at least told if the error is caused by me or what

**Comment by casperiv0** [comment]
This won't be fixed unfortunately. You can self-host home-inventory. It's unable to connect to the database because it's in a "paused" state on Supabase.

**Comment by Ngoakor12** [comment]
> This won't be fixed unfortunately. You can self-host home-inventory. It's unable to connect to the database because it's in a "paused" state on Supabase.

No problem, I understand. I just wanted to confirm whether it was intentional or not.
